### ISSUE TITLE
Itemdata class is missing in syntax highlighting.

### ISSUE THREAD

**Issue by Alucard648** [bobbylight/ZScriptLanguageSupport#1]
"Itemdata", according to Zcsript manual, is the class that handles most of item properties, like Power, level, item class, InitD values, etc. This data is mostly used by item scripts by referring "this" as pointer to Itemdata of item that ran rhe script.  But in Rtext, it is not recognized as viable function for code highlighting and autocompletion, unlike FFC class, Lweapon & Eweapon classes etc. 
Also attempt too put Game->InitD[x] in the script results in compilation error: "That pointer does not have a variable InitD". This is because documentation erroneously refers it to "Game" namespace, not "Itemdata". Actually, Itemdata->InitD compiles fine and properly refers to item`s init D values stored in the quest file.
Hoping, "necroposting" new issues in old repositories in Github does not result in ban...

**Comment by bobbylight** [comment]
Is there documentation on Itemdata?  Not really being a ZQuest user, just a fan, I'm not very familiar with it myself.  I'm currently loading some `Itemdata`-related stuff (Amount, Max, MaxIncrement, ...), but I didn't know where to make it available.  For example, it is not a global variable, such as `Game` or `Link`, is it?

Are you saying that all `Itemdata` fields are available off of `this`, e.g. `this-><whatever>`?  Is this true only for `item`-type scripts?

The best/only doc I know of for ZScript is on [this wiki](http://www.shardstorm.com/ZCwiki/Category:ZScript), though it may be somewhat outdated.  Note though that the foundation for code completion comes from the doc shipped with 2.5.0 final (I think).  I know that's a little old as there have been one or two point releases since.

**Comment by Alucard648** [comment]
Here is a bit about itemdata class in latest version of Zscript (2.5.2)
//=========================================
//--- Itemdata Functions and Variables ---
//=========================================

class itemdata{
    /**
    \* The original values of the item's 8 D input values are they are stored in the
    \* .qst file, regardles of whether they have been modified by ZScript.
    _/
    float InitD[];  
    /_*
    \* Loads the item this itemdata is attributed to's name into 'buffer'
    _/
    void GetName(int buffer[]);
    /_*
    \* The kind of item to which this class belongs (swords, boomerangs,
    \* potions, etc.) Use the IC_ constants in std.zh to set or compare this
    \* value.
    _/
    int Family;
    /_*
    \* The level of this item. Higher-level items replace lower-level items
    \* when they are picked up.
    _/
    int Level;
    /_*
    \* The item's power, for most items this is amount of damage dealt but is
    \* used for other values in some items (ie. Roc's Feather)
    _/
    int Power;
    /_*
    \* Corresponds to the "Increase Amount" entry in the Item Editor.
    \* The value of this data member can have two meanings:
    \* If Amount & 0x8000 is 1, the drain counter for this item is set
    \* to Amount & 0x3FFF. The game then slowly fills the counter of this item
    \* (see Counter below) out of the drain counter. Gaining rupees uses the
    \* drain counter, for example.
    \* is set to Amount when the item is picked up.
    \* If Amount & 0x8000 is 0, the counter of this item is increased, if
    \* Amount & 0x4000 is 1, or decreased, if Amount & 0x4000 is 0, by
    \* Amount & 0x3FFF when the item is picked up.
    _/
    int Amount;
    /_*
    \* Corresponds to the "Increase Counter Max" entry in the Item Editor.
    \* In conjunction with Max (see below) this value controls how the
    \* maximum value of the counter of this item (see Counter below) is
    \* modified when the item is picked up. If MaxIncrement is nonzero at that
    \* time, the counter's new maximum value is at that time set to the
    \* minimum of its current value plus MaxIncrement, and Max.
    \* If Max is less than the current maximum of the counter, Max is ignored
    \* and that maximum is used instead.
    _/
    int MaxIncrement;  
    /_*
    \* Corresponds to the "But Not Above" entry in the Item Editor.
    \* In conjunction with MaxIncrement (see above) this value controls how
    \* the maximum value of the counter of this item (see Counter below) is
    \* modified when the item is picked up. If MaxIncrement is nonzero at that
    \* time, the counter's new maximum value is at that time set to the
    \* minimum of its current value plus MaxIncrement, Max.
    \* If Max is less than the current maximum of the counter, Max is ignored
    \* and that maximum is used instead.
    \* Notice that as a special case, if Max = MaxIncrement, the counter's
    \* maximum value will be forced equal to Max.
    _/
    int Max;
    /_*
    \* Corresponds to the "Equipment Item" checkbox in the Item Editor.
    \* If true, Link will keep the item, and it will show up as an item or
    \* equipment in the subscreen. If false, it may modify the current value
    \* or maximum value of its counter (see Counter below), then disappear.
    \* The White Sword and Raft, for instance, have Keep true, and keys and
    \* rupees have Keep false.
    _/
    bool Keep;
    /_*
    \* Corresponds to the "Counter Reference" entry in the Item Editor.
    \* The game counter whose current and modified values might be modified
    \* when the item is picked up (see Amount, Max, and MaxIncrement above.)
    \* Use the CT_ constants in std.zh to set or compare this value.
    _/
    int Counter;
    /_*
    \* Corresponds to the "Sound" entry on the action tab in the Item Editor.
    */
    int UseSound;  
}; //itemdata

@bobbylight Are you saying that all Itemdata fields are available off of this, e.g. this-><whatever>? Is this true only for item-type scripts?

Yes and Yes

**Comment by bobbylight** [comment]
@Alucard648, I think I've addressed everything you brought up.  Can you try it out and see what you think?  Windows releases of the demo can now be grabbed off of [GitHub directly](https://github.com/bobbylight/ZScriptLanguageSupport/releases).
